# Generated by Django 4.0.6 on 2024-04-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_criacao', models.IntegerField()),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField()),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha5Ex2.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=10)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='ficha5Ex2.disco')),
            ],
        ),
    ]
