# Generated by Django 4.0.6 on 2024-04-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivais.localizacao'),
        ),
    ]
