# Generated by Django 4.0.6 on 2024-04-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0003_rename_nome_localizacao_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
