# Generated by Django 4.0.6 on 2024-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0005_remove_localizacao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='localizacao',
            name='festivais',
            field=models.ManyToManyField(to='festivais.festival'),
        ),
    ]
