# Generated by Django 4.0.6 on 2024-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0007_festival_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='imagem',
        ),
        migrations.AddField(
            model_name='banda',
            name='imagem',
            field=models.ImageField(default='', upload_to='bandas'),
            preserve_default=False,
        ),
    ]
