# Generated by Django 4.0.6 on 2024-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_disciplina_curso_curso_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='projetos',
            field=models.ManyToManyField(to='curso.projeto'),
        ),
    ]
