# Generated by Django 4.0.6 on 2024-05-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_projeto_disciplina_disciplina_projetos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nome_projeto',
            new_name='nome',
        ),
    ]
