# Generated by Django 4.0.6 on 2024-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='biografia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='musicas',
            field=models.ManyToManyField(blank=True, to='bandas.musica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='album',
            field=models.ManyToManyField(blank=True, to='bandas.album'),
        ),
    ]
