# Generated by Django 4.0.6 on 2024-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_musica_biografia_alter_album_musicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='biografia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
